import{a as L,S as b,i as a}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const v="44507065-2e810e6cd55f29a257fa3dc75";async function f(e,r=1){const s=`https://pixabay.com/api/?key=${v}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${r}`;try{return(await L.get(s)).data}catch(n){throw console.error("Axios error: ",n),n}}function m(e,r,s=!1){const n=document.getElementById("gallery"),t=e.map(o=>E(o)).join("");s?n.insertAdjacentHTML("beforeend",t):n.innerHTML=t,r.refresh()}function E(e){return`
  <div class="gallery-item-container">  
  <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" title="${e.tags}" loading="lazy" />
      <div class="info">
        <p><span>Likes:</span> ${e.likes}</p>
        <p><span>Views:</span> ${e.views}</p>
        <p><span>Comments:</span> ${e.comments}</p>
        <p><span>Downloads:</span> ${e.downloads}</p>
      </div>
    </a>
  </div>
  `}function h(){const e=document.getElementById("loader");e.style.display="block"}function g(){const e=document.getElementById("loader");e.style.display="none"}let w=new b(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"title",captionPosition:"bottom",captionDelay:250,animationSpeed:250,fadeSpeed:300,close:!0,showCounter:!0});const I=document.getElementById("search-form"),y=document.getElementById("search-input"),l=document.getElementById("load-more");let c=1,i="",p=0,d=0;I.addEventListener("submit",async e=>{if(e.preventDefault(),i=y.value.trim(),!i){a.error({title:"Error",message:"Please enter a search query."});return}c=1,l.style.display="none",h();try{const r=await f(i,c);p=r.totalHits,d=r.hits.length,r.hits.length===0?a.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(r.hits,w),y.value="",d<p&&(l.style.display="block"))}catch{a.error({title:"Error",message:"An error occurred while fetching images."})}finally{g()}});l.addEventListener("click",async()=>{c+=1,h();try{const e=await f(i,c);d+=e.hits.length,m(e.hits,w,!0),$(),d>=p&&(l.style.display="none",a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"An error occurred while fetching images."})}finally{g()}});function $(){const{height:e}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
